### ISSUE TITLE
Problem with polars during parsing with big bam

### ISSUE THREAD

**Issue by NicolasProvencher** [TRISTAN-ORF/RiboTIE#8]
Hi, sorry to bother again.

I made polar crash during the parsing step and it seems that it is caused by a .bam that might be too big, here is the error transcript

<details>
  <summary>Click to expand!</summary>
  
```
  thread '<unnamed>' panicked at crates/polars-core/src/chunked_array/ops/chunkops.rs:83:62:
polars' maximum length reached. Consider installing 'polars-u64-idx'.: TryFromIntError(())
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Processed assembly data restored (/home/noxatras/scratch/riboformer/reference/Homo_sapiens.GRCh38.109.chr.h5)
--> parsed transcriptome directory found, assembly information can not be re-processed (for existing h5 files).
Loading in GSE56924...
Traceback (most recent call last):
  File "/opt/conda/envs/ribo/bin/riboformer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/conda/envs/ribo/lib/python3.11/site-packages/transcript_transformer/riboformer.py", line 106, in main
    process_ribo_data(
  File "/opt/conda/envs/ribo/lib/python3.11/site-packages/transcript_transformer/data.py", line 131, in process_ribo_data
    df = ctx.sql("SELECT reference, start, sequence FROM test").to_polars()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/ribo/lib/python3.11/site-packages/polars/dataframe/frame.py", line 390, in __init__
    self._df = arrow_to_pydf(
               ^^^^^^^^^^^^^^
  File "/opt/conda/envs/ribo/lib/python3.11/site-packages/polars/utils/_construction.py", line 1540, in arrow_to_pydf
    pydf = pydf.rechunk()
           ^^^^^^^^^^^^^^
pyo3_runtime.PanicException: polars' maximum length reached. Consider installing 'polars-u64-idx'.: TryFromIntError(())

```
</details>

The size of the bam file is 73G
I checked and my job only used a 3rd of the memory given to it (37% of 1.5tb of ram)
I am unfamiliar with polars so I dont know If i attained the technical limit of polars or if its something easily fixable

If this is to complex to fix just let me know I will try to find a workaround in my workflow to reduce the size of my files

As always thank you for your amazing tool and the support you are giving me

Best 

Nicolas

**Comment by jdcla** [comment]
Hey Nicolas, 
Thank you for the continued bug reports.

Have you tried installing polars-u64-idx, as suggested by the bug report? 

`pip install polars-u64-idx`

let me know if this works!

**Comment by NicolasProvencher** [comment]
Ok ill try to add it in the dependency in my container, ill update you once i have the results.
might take a few days because I'm running everything on slurm and somethine jobs take a bit to start

**Comment by jdcla** [comment]
Sounds great, I might add it as a default dependency, but I don't have a 73GB Bam to test this on. Make sure to check out the new features on parallelization offered by v0.8.0 that I released today.

**Comment by jdcla** [comment]
Hey Nicolas, maybe hold of using ribotie v0.8.0 for a bit, I might have found a bug.

**Comment by jdcla** [comment]
@NicolasProvencher Any update on this?

FYI: The 0.8.1 update solved the issue i mentioned in my previous post, so you should be good to go to try this version out.  Check the readme on info on using the `--parallel` flag.

**Comment by NicolasProvencher** [comment]
It crashed due to time limit (my fault) but so far its promising, I'll let you know when i have the result of the rerun.

And thanks for the update

**Comment by NicolasProvencher** [comment]
Hi it seems like i still get the error when i tried to install the packages it ask,
So it seems it isnt able to see the installed packages
when i check the versions, they are different i wonder if thats it

polars                    0.20.19            
polars-u64-idx            0.20.25
I'm going to try and make an environment with both version being the same and ill update you.


If you think of anything else that could make it so polar doesnt find its u64-uidx addon let me know

**Comment by NicolasProvencher** [comment]
Update, even with the matching version i get the same error
It seems to me polar doesnt actually know its add-on is there.
By looking at polars doc it is unclear if you need both the polar and polar-u64 package or if you need to replace the polar by polar-u64 so imma try and uninstall polar to replace it by polar u.64

the only other explenation i have is that in the code when calling polar we need to tell him use u64 or something

Ill update after i have the result of my next test

**Comment by jdcla** [comment]
I think it might be a problem related to the fact that BioBear is used for data loading of .bam files, which they afterwards convert to polars, so this issue might have to be taken up with them.

**Comment by jdcla** [comment]
Alright, v0.8.3 is updated to include some biobear updates that could fix this issue. If you have time, checking in on this would be appreciated!

**Comment by NicolasProvencher** [comment]
The update did not fix my issue, polars-u64-idx was not installed so I just started a run with it.

But this 73g files is multiple files from the same study merged so if this is too complicated to fix imma try and rerun it without the merge and merge the results after

**Comment by jdcla** [comment]
Ok, please note that multiple bams can be easily combined by RiboTie already by formatting the 'samples' in the config file as such, see template.yml for more info on this. RiboTIE simply sums the reads for multiple files, which equals to merging the files beforehand. I created this feature exactly to evade hassles from merging independent files into massive single files. This also allows more flexibility when adding files later (e.g. no need to remap the whole new file).

Hope this helps.
